# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - NBAGetFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: 'NBAGetFunction'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/NBAGetFunction' # Ensure function app path is correct
  PYTHON_VERSION: '3.12' # Azure Functions does not support Python 3.12 yet

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify installed dependencies
        run: pip check || true  # Ensures no broken dependencies

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip NBAGetFunction host.json requirements.txt -x "venv/*" ".git/*" ".github/*" "DataRequest.txt" "desktop.ini"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for JWT authentication
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D7C7B0FB4BD14A0FBF003EBD2D8E9157 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_06831B5FE2174653BD115F546E1A8A24 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A625E7F80C3C4C5E8FCE63C55A410DE8 }}

      - name: Deploy to Azure Functions via ZipDeploy
        run: |
          az functionapp deployment source config-zip \
            --resource-group Resource_Group1 \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --src release.zip
