# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - NBAGetFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
            
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies locally
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          # First install the dependencies normally
          pip install -r requirements.txt
          # Then install dependencies into a folder so they get packaged
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Zip artifact for deployment
        run: |
          # Package the function folder, host.json, requirements.txt, and the dependency folder
          zip -r release.zip NBAGetFunction host.json requirements.txt .python_packages -x "venv/*" "*.git*" ".github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip



  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D7C7B0FB4BD14A0FBF003EBD2D8E9157 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_06831B5FE2174653BD115F546E1A8A24 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A625E7F80C3C4C5E8FCE63C55A410DE8 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'NBAGetFunction'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}